---
title: "Busdata Cluster"
runtime: shiny
output: 
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(shiny)
library(plotly)
library(DBI)
library(stringr)
library(RColorBrewer)

```

```{r, out.width="100%"}

busdata_garagens_shape <- read_csv("garagensdata/garagens_shape.csv") |>
  group_by(garagem)

busdata_garagens_grandes <- read_csv("garagensdata/dados_cluster_filtrado.csv") |>
  filter(id_agrupamento != 0) |> 
  slice_sample(prop = 0.3, replace = FALSE)

busdata_garagens_pequenas <- read_csv("garagensdata/dados_cluster_pequenos.csv") |>
  filter(id_agrupamento != 0)

fig <- plot_ly(type = "scattermapbox", mode = "markers") |>
  add_trace(
    data = busdata_garagens_shape,
    lat = ~lat,
    lon = ~long,
    color = ~garagem,
    opacity = 0.5,
    mode = "markers+lines",
    marker = list(color = "black"),
    hoverinfo = "text",
    text = ~paste(
      "Lat:", lat,
      "Long:" , long, "<br>",
      "Garagem:", garagem
    ),
    name = "Garagens Shape"
  ) |>
  add_trace(
    data = busdata_garagens_grandes,
    lat = ~lat,
    lon = ~long,
    color = ~id_agrupamento,
    opacity = 0.5,
    marker = list(color = "darkorchid"),
    hoverinfo = "text",
    text = ~paste(
      "Lat:", lat,
      "Long:" , long, "<br>",
      "Agrupamento:", id_agrupamento
    ),
    name = "Garagens Grandes"
  ) |>
  add_trace(
    data = busdata_garagens_pequenas,
    lat = ~lat,
    lon = ~long,
    color = ~id_agrupamento,
    opacity = 0.5,
    marker = list(color = "brown2"),
    hoverinfo = "text",
    text = ~paste(
      "Lat:", lat,
      "Long:" , long, "<br>",
      "Agrupamento:", id_agrupamento
    ),
    name = "Garagens Pequenas"
  ) |>
  layout(
    mapbox = list(
      style = "open-street-map",
      zoom = 9.5,
      center = list(lat = -22.9, lon = -43.45)
    )
  ) %>% 
  hide_colorbar() %>% 
  suppressWarnings() # Remove Warnings 
  
fig


```

### Garagens Encontradas

```{r, out.width="100%"}

busdata_garagens_shape <- read_csv("garagensdata/garagens_shape.csv") |>
  mutate(
    classificacao = if_else(
      garagem == 03 | garagem == 04 | garagem == 05 | garagem == 07 | garagem == 09 | 
      garagem == 15 | garagem == 17 | garagem == 18 | garagem == 22 | garagem == 23 | 
      garagem == 27 | garagem == 28 | garagem == 29 | garagem == 30 | garagem == 32 | 
      garagem == 34 | garagem == 35 | garagem == 36 | garagem == 39 | garagem == 41 | 
      garagem == 43 | garagem == 45 | garagem == 47 | garagem == 48 | garagem == 49 | 
      garagem == 50,
      "Verde",
      "Amarelo"
    )
  ) |>
  group_by(garagem)

busdata_garagens_grandes <- read_csv("garagensdata/dados_cluster_filtrado.csv") |>
  filter(id_agrupamento != 0) |> 
  slice_sample(prop = 0.3, replace = FALSE) |>
  mutate(
    classificacao = if_else(
      id_agrupamento == 01 | id_agrupamento == 02 | id_agrupamento == 03 | id_agrupamento == 12 | 
      id_agrupamento == 13 | id_agrupamento == 20 | id_agrupamento == 26,
      "Vermelho",
      "Verde"
    )
  )

busdata_garagens_pequenas <- read_csv("garagensdata/dados_cluster_pequenos.csv") |>
  filter(id_agrupamento != 0) |>
  mutate(
    classificacao = if_else(
      id_agrupamento == 06 | id_agrupamento == 17,
      "Verde",
      "Vermelho"
    )
  )

fig <- plot_ly(type = "scattermapbox", mode = "markers", colors = c("red", "green", "yellow")) |>
  add_trace(
    data = busdata_garagens_shape,
    lat = ~lat,
    lon = ~long,
    color = ~classificacao,
    opacity = 0.5,
    mode = "markers+lines",
    hoverinfo = "text",
    text = ~paste(
      "Lat:", lat,
      "Long:" , long, "<br>",
      "Garagem:", garagem
    ),
    name = "Garagens Shape"
  ) |>
  add_trace(
    data = busdata_garagens_grandes,
    lat = ~lat,
    lon = ~long,
    color = ~classificacao,
    opacity = 0.5,
    hoverinfo = "text",
    text = ~paste(
      "Lat:", lat,
      "Long:" , long, "<br>",
      "Agrupamento:", id_agrupamento
    ),
    name = "Garagens Grandes"
  ) |>
  add_trace(
    data = busdata_garagens_pequenas,
    lat = ~lat,
    lon = ~long,
    color = ~classificacao,
    opacity = 0.5,
    hoverinfo = "text",
    text = ~paste(
      "Lat:", lat,
      "Long:" , long, "<br>",
      "Agrupamento:", id_agrupamento
    ),
    name = "Garagens Pequenas"
  ) |>
  layout(
    mapbox = list(
      style = "open-street-map",
      zoom = 9.5,
      center = list(lat = -22.9, lon = -43.45)
    )
  ) %>% 
  hide_colorbar() %>% 
  suppressWarnings() # Remove Warnings 

fig

```

```{r}

num_garagem <- busdata_garagens_shape |>
  distinct(garagem) |>
  nrow()

num_garagem_encontradas <- busdata_garagens_shape |>
  filter(classificacao != "Amarelo") |>
  distinct(garagem) |>
  nrow()

# ------------------------------------------------------------------------------

num_garagem_grande <- busdata_garagens_grandes |>
  distinct(id_agrupamento) |>
  nrow()

num_garagem_encontradas_grande <- busdata_garagens_grandes |>
  filter(classificacao != "Vermelho") |>
  distinct(id_agrupamento) |>
  nrow()

# ------------------------------------------------------------------------------

num_garagem_pequena <- busdata_garagens_pequenas |>
  distinct(id_agrupamento) |>
  nrow()

num_garagem_encontradas_pequena <- busdata_garagens_pequenas |>
  filter(classificacao != "Vermelho") |>
  distinct(id_agrupamento) |>
  nrow()

```



Garagens Encontradas do Arquivo: `r num_garagem_encontradas`/`r num_garagem`

Garagens Grandes Encontradas Corretamente: `r num_garagem_encontradas_grande`/`r num_garagem_grande`

Gargens Pequenas Encontradas Corretamente: `r num_garagem_encontradas_pequena`/`r num_garagem_pequena`
